/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

/**
 *
 * @author 91734
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import sun.applet.Main;
import java.util.Date;

/**
 *
 * @author HP
 */
public class MysqlConnectionProvider {

    public Connection MysqlConnectionProvider() {
     try{
       Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ asian_paints?useSSL=false","root","1234");
          System.out.println("database connected");
           return con;
    }
     catch(Exception e)
     {
         return null;
     }
    }
    
   public Statement MysqlStatement(){
       try{
           Statement statement =MysqlConnectionProvider().createStatement();
           
          return statement ;
          
       }
       catch(Exception e){ 
       return null;
       
       }
       
           
       }
   
   public ResultSet MySqlResultSet(String s){
        try{
            ResultSet resultSet=(ResultSet) MysqlStatement().executeQuery(s);
           return resultSet;
        }
        catch(Exception e){
            return null;
        }
   }
   public void updateQuery(int uid,String pass){
       try{
           Connection con=null;
     con=MysqlConnectionProvider();
           String query="UPDATE `asian_paints`.`user_details`\n" +
"set password=? \n" +
"where uid= ?;";
           PreparedStatement preparedStatement=con.prepareStatement(query);
           preparedStatement.setString(1,pass);
       preparedStatement.setInt(2,uid);
        preparedStatement.executeUpdate();
      
       con.close();
       }catch(Exception e){
           
       }
   }
  

    public void InsertData( String Username, String password, String first_name, String last_name, String user_phoneNo, String user_email, String user_address) {
              try{String query ="Insert into `user_details`(username,password,f_name,l_name,user_phone,email,user_addrs)"+"values(?,?,?,?,?,?,?)";
     Connection con=null;
     con=MysqlConnectionProvider();
     ResultSet rs;
             PreparedStatement preparedStatement=con.prepareStatement(query);
             //rs=preparedStatement.getGeneratedKeys();
            // preparedStatement.executeUpdate();
            // rs.next();
            // int autoGeneratedId =rs.getInt(1);
     
       preparedStatement.setString(1,Username);
       preparedStatement.setString(2,password);
       preparedStatement.setString(3,first_name);
       preparedStatement.setString(4,last_name);
       preparedStatement.setString(5,user_phoneNo);
       preparedStatement.setString(6,user_email);
       preparedStatement.setString(7,user_address);
       preparedStatement.execute();
      
       con.close();
      }
      
      catch(SQLException e){
          System.out.println("Got Exception");
          System.out.println(e.toString());
          
      }
    
        //To change body of generated methods, choose Tools | Templates.
    }
  public void insertIntoBill(int order_id){
        try{
             Connection con=null;
     con=MysqlConnectionProvider();
            SimpleDateFormat formatter=new SimpleDateFormat("yyyy/MM/dd");
            Date d =new Date();
     String date=formatter.format(d);
            //date = String.valueOf(d.getDay())+"/"+String.valueOf(d.getMonth())+"/";
String.valueOf(d.getYear());
     String query=" INSERT INTO `asian_paints`.`bill`(orderid,date)values(?,?)";


             PreparedStatement preparedStatement=con.prepareStatement(query);
       
       preparedStatement.setString(1,String.valueOf(order_id));
       preparedStatement.setString(2,String.valueOf(date));
          preparedStatement.execute();
            System.out.println("data inserted into bill table");
       con.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
  
 public void insertIntoOrderTable(int orderId,String product_id, int quantity){
      try{
             Connection con=null;
     con=MysqlConnectionProvider();
     
     String query=" INSERT INTO `asian_paints`.`orderedproducts`(order_id,product_id,qnty)values(?,?,?)";


             PreparedStatement preparedStatement=con.prepareStatement(query);
       preparedStatement.setInt(1,orderId);
       preparedStatement.setString(2,product_id);
       preparedStatement.setInt(3,quantity);
          preparedStatement.execute();
       
       con.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }

 }

/*class MyClass{
    public static void main(String[] args) {
        MysqlConnectionProvider p =new MysqlConnectionProvider();
        p.insertIntoBill(10,1,"10/12/12" );
    }
            
          
}*/