/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exterior;

import DealerLoginForm.DealerLogin;
import HomeMenu.Menu;
import added.addedToBill;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdbc.MysqlConnectionProvider;

/**
 *
 * 
 */
public class Exterior extends javax.swing.JFrame {

    /**
     * Creates new form Exterior
     */
    public Exterior() {
        initComponents();
        hideColors();
        resizing_defaultImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        colorName = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        grayButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        greenButtton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        displayColor = new javax.swing.JLabel();
        r7 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        r5 = new javax.swing.JLabel();
        r6 = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        color_code = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        y2 = new javax.swing.JLabel();
        y3 = new javax.swing.JLabel();
        y4 = new javax.swing.JLabel();
        y5 = new javax.swing.JLabel();
        y6 = new javax.swing.JLabel();
        y7 = new javax.swing.JLabel();
        gr1 = new javax.swing.JLabel();
        w3 = new javax.swing.JLabel();
        w4 = new javax.swing.JLabel();
        w5 = new javax.swing.JLabel();
        w6 = new javax.swing.JLabel();
        w7 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        gr2 = new javax.swing.JLabel();
        gr3 = new javax.swing.JLabel();
        gr4 = new javax.swing.JLabel();
        gr5 = new javax.swing.JLabel();
        gr6 = new javax.swing.JLabel();
        gr7 = new javax.swing.JLabel();
        color_quantity = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        bg_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXTERIOR PAINTS");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label4.setText("X");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 102, 76));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label6.setText("E");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 102, 76));

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label14.setText("T");
        jPanel2.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 102, 76));

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label15.setText("E");
        jPanel2.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 102, 76));

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label16.setText("R");
        jPanel2.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 102, 76));

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label17.setText("R");
        jPanel2.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 102, 76));

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label18.setText("I");
        jPanel2.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 102, 76));

        label19.setAlignment(java.awt.Label.CENTER);
        label19.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label19.setText("O");
        jPanel2.add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 102, 76));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colorName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        colorName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(colorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));

        redButton.setBackground(new java.awt.Color(255, 0, 0));
        redButton.setText("RED");
        redButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redButtonMouseClicked(evt);
            }
        });
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        jPanel1.add(redButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 30));

        blueButton.setBackground(java.awt.Color.blue);
        blueButton.setText("BLUE");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(blueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, 30));

        grayButton.setBackground(java.awt.Color.gray);
        grayButton.setText("GREY");
        grayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grayButtonMouseClicked(evt);
            }
        });
        jPanel1.add(grayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 80, 30));

        whiteButton.setBackground(new java.awt.Color(255, 255, 255));
        whiteButton.setText("WHITE");
        whiteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteButtonMouseClicked(evt);
            }
        });
        jPanel1.add(whiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 80, 30));

        yellowButton.setBackground(java.awt.Color.yellow);
        yellowButton.setText("YELLOW");
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(yellowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 90, 30));

        greenButtton.setBackground(java.awt.Color.green);
        greenButtton.setText("GREEN");
        greenButtton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenButttonMouseClicked(evt);
            }
        });
        jPanel1.add(greenButtton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, 30));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECT COLOR");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), java.awt.Color.white, new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 280, 60));

        displayColor.setBackground(new java.awt.Color(255, 255, 255));
        displayColor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        displayColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), java.awt.Color.white, new java.awt.Color(255, 255, 255)));
        displayColor.setOpaque(true);
        jPanel1.add(displayColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 280, 320));

        r7.setOpaque(true);
        r7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r7MouseClicked(evt);
            }
        });
        jPanel1.add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 60, 50));

        b7.setOpaque(true);
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 60, 50));

        r2.setOpaque(true);
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 50));

        r3.setOpaque(true);
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 60, 50));

        r4.setOpaque(true);
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        jPanel1.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 60, 50));

        r5.setOpaque(true);
        r5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r5MouseClicked(evt);
            }
        });
        jPanel1.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 60, 50));

        r6.setOpaque(true);
        r6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r6MouseClicked(evt);
            }
        });
        jPanel1.add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 60, 50));

        r1.setOpaque(true);
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        jPanel1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 50));

        y1.setOpaque(true);
        y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y1MouseClicked(evt);
            }
        });
        jPanel1.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 60, 50));

        b2.setOpaque(true);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, 50));

        b3.setOpaque(true);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 60, 50));

        b4.setOpaque(true);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 60, 50));

        b5.setOpaque(true);
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 60, 50));

        b6.setOpaque(true);
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 60, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COLOR CODE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COLOR NAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUALITY:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QUANTITY:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ltr");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 50, 30));

        color_code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        color_code.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(color_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 70, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACE", "ULTIMA", "APEX" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 170, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exterior/icons8_shopping_cart_48px_1.png"))); // NOI18N
        jLabel10.setText("ADD TO BILL");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 180, 60));

        jLabel11.setBackground(new java.awt.Color(204, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exterior/icons8_back_arrow_26px.png"))); // NOI18N
        jLabel11.setText("BACK");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 100, 40));

        b1.setOpaque(true);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, 50));

        g2.setOpaque(true);
        g2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g2MouseClicked(evt);
            }
        });
        jPanel1.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 60, 50));

        g3.setOpaque(true);
        g3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g3MouseClicked(evt);
            }
        });
        jPanel1.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 60, 50));

        g4.setOpaque(true);
        g4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g4MouseClicked(evt);
            }
        });
        jPanel1.add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 60, 50));

        g5.setOpaque(true);
        g5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g5MouseClicked(evt);
            }
        });
        jPanel1.add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 60, 50));

        g6.setOpaque(true);
        g6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g6MouseClicked(evt);
            }
        });
        jPanel1.add(g6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 60, 50));

        g7.setOpaque(true);
        g7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g7MouseClicked(evt);
            }
        });
        jPanel1.add(g7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 60, 50));

        g1.setOpaque(true);
        g1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked(evt);
            }
        });
        jPanel1.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 60, 50));

        y2.setOpaque(true);
        y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y2MouseClicked(evt);
            }
        });
        jPanel1.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 50));

        y3.setOpaque(true);
        y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y3MouseClicked(evt);
            }
        });
        jPanel1.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 60, 50));

        y4.setOpaque(true);
        y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y4MouseClicked(evt);
            }
        });
        jPanel1.add(y4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 60, 50));

        y5.setOpaque(true);
        y5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y5MouseClicked(evt);
            }
        });
        jPanel1.add(y5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 60, 50));

        y6.setOpaque(true);
        y6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y6MouseClicked(evt);
            }
        });
        jPanel1.add(y6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 60, 50));

        y7.setOpaque(true);
        y7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y7MouseClicked(evt);
            }
        });
        jPanel1.add(y7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 60, 50));

        gr1.setOpaque(true);
        gr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr1MouseClicked(evt);
            }
        });
        jPanel1.add(gr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 60, 50));

        w3.setOpaque(true);
        w3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w3MouseClicked(evt);
            }
        });
        jPanel1.add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 60, 50));

        w4.setOpaque(true);
        w4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w4MouseClicked(evt);
            }
        });
        jPanel1.add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 60, 50));

        w5.setOpaque(true);
        w5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w5MouseClicked(evt);
            }
        });
        jPanel1.add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 60, 50));

        w6.setOpaque(true);
        w6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w6MouseClicked(evt);
            }
        });
        jPanel1.add(w6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 60, 50));

        w7.setOpaque(true);
        w7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w7MouseClicked(evt);
            }
        });
        jPanel1.add(w7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 60, 50));

        w2.setOpaque(true);
        w2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w2MouseClicked(evt);
            }
        });
        jPanel1.add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 60, 50));

        w1.setOpaque(true);
        w1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w1MouseClicked(evt);
            }
        });
        jPanel1.add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 60, 50));

        gr2.setOpaque(true);
        gr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr2MouseClicked(evt);
            }
        });
        jPanel1.add(gr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 60, 50));

        gr3.setOpaque(true);
        gr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr3MouseClicked(evt);
            }
        });
        jPanel1.add(gr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 60, 50));

        gr4.setOpaque(true);
        gr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr4MouseClicked(evt);
            }
        });
        jPanel1.add(gr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 60, 50));

        gr5.setOpaque(true);
        gr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr5MouseClicked(evt);
            }
        });
        jPanel1.add(gr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 60, 50));

        gr6.setOpaque(true);
        gr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr6MouseClicked(evt);
            }
        });
        jPanel1.add(gr6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 60, 50));

        gr7.setOpaque(true);
        gr7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gr7MouseClicked(evt);
            }
        });
        jPanel1.add(gr7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 60, 50));

        color_quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        color_quantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "10", "15", "25" }));
        jPanel1.add(color_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, 30));

        bg_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exterior/ext222.jpg"))); // NOI18N
        bg_image.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(bg_image, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
//settting background color
        y1.setBackground(new java.awt.Color(225, 193, 110));

        y2.setBackground(new java.awt.Color(255, 255, 143));

        y3.setBackground(new java.awt.Color(228, 208, 10));

        y4.setBackground(new java.awt.Color(255, 215, 0));

        y5.setBackground(new java.awt.Color(255, 192, 0));

        y6.setBackground(new java.awt.Color(255, 250, 160));

        y7.setBackground(new java.awt.Color(255, 255, 0));

            
        //set visibility
        y1.setVisible(true);

        y2.setVisible(true);

        y3.setVisible(true);

        y4.setVisible(true);

        y5.setVisible(true);

        y6.setVisible(true);

        y7.setVisible(true);

                // TODO add your handling code here:
      
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
        // TODO add your handling code here:
            // TODO add your handling code here:
displayColor.setBackground(new Color(0,0,128));   
displayColor.setText("navy_Ext");
colorName.setText("navy_Ext");
color_code.setText("2047");
    }//GEN-LAST:event_b7MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
        // TODO add your handling code here:
                displayColor.setBackground(new Color(255,160,122));  
displayColor.setText("lightsalmon_Ext");
colorName.setText("lightsalmon_Ext");
color_code.setText("2001");
    }//GEN-LAST:event_r2MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
        // TODO add your handling code here:
        displayColor.setBackground(new Color(233,150,122));        // TODO add your handling code here:
displayColor.setText("darksalmon_Ext");
colorName.setText("darksalmon_Ext");
color_code.setText("2002");
    }//GEN-LAST:event_r3MouseClicked

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
        // TODO add your handling code here:
        displayColor.setBackground(new Color(240,128,128));        // TODO add your handling code here:
displayColor.setText("lightcoral_Ext");
colorName.setText("lightcoral_Ext");
color_code.setText("2003");
    }//GEN-LAST:event_r4MouseClicked

    private void r5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r5MouseClicked
        // TODO add your handling code here:
        displayColor.setBackground(new Color(205,92,92));
displayColor.setText("indianred_Ext");
colorName.setText("indianred_Ext");
color_code.setText("2004");
    }//GEN-LAST:event_r5MouseClicked

    private void r6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r6MouseClicked
        // TODO add your handling code here:
        displayColor.setBackground(new Color(220,20,60));
displayColor.setText("crimson_Ext");
colorName.setText("crimson_Ext");
color_code.setText("2005");
    }//GEN-LAST:event_r6MouseClicked

    private void r7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r7MouseClicked
     displayColor.setBackground(new Color(178,34,34));
displayColor.setText("firebrick_Ext");
colorName.setText("firebrick_Ext"); 
color_code.setText("2006");// TODO add your handling code here:
    }//GEN-LAST:event_r7MouseClicked

    private void redButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redButtonMouseClicked
        // TODO add your handling code here:
        r1.setBackground(new Color(250,128,114));
//label6.setBackground(new Color(255,0,0));
r2.setBackground(new Color(255,160,122));
r3.setBackground(new Color(233,150,122));
r4.setBackground(new Color(240,128,128));
r5.setBackground(new Color(205,92,92));
r6.setBackground(new Color(220,20,60));
r7.setBackground(new Color(178,34,34));

//SET VISIBILITY
 r1.setVisible(true);
        r2.setVisible(true);
        r3.setVisible(true);
        r4.setVisible(true);
        r5.setVisible(true);
        r6.setVisible(true);
        r7.setVisible(true);
        

    }//GEN-LAST:event_redButtonMouseClicked

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        r1.setBackground(new Color(250,128,114));
//label6.setBackground(new Color(255,0,0));
r2.setBackground(new Color(255,160,122));
r3.setBackground(new Color(233,150,122));
r4.setBackground(new Color(240,128,128));
r5.setBackground(new Color(205,92,92));
r6.setBackground(new Color(220,20,60));
r7.setBackground(new Color(178,34,34));

//SET VISIBILITY
 r1.setVisible(true);
        r2.setVisible(true);
        r3.setVisible(true);
        r4.setVisible(true);
        r5.setVisible(true);
        r6.setVisible(true);
        r7.setVisible(true);
    }//GEN-LAST:event_redButtonActionPerformed

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
displayColor.setBackground(new Color(250,128,114)); 
displayColor.setText("Salmon_Ext");
colorName.setText("Salmon_Ext"); 
color_code.setText("2000");// TODO add your handling code here:
    }//GEN-LAST:event_r1MouseClicked

    private void y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y1MouseClicked
      // TODO add your handling code here:
        displayColor.setBackground(new java.awt.Color(225, 193, 110));
         displayColor.setText(" Brass_Ext");
         colorName.setText(" Brass_Ext");
         color_code.setText("2025");// TODO add your handling code here:
    }//GEN-LAST:event_y1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
       displayColor.setBackground(new Color(106,90,205));
displayColor.setText("slateblue_Ext");
colorName.setText("slateblue_Ext");
color_code.setText("2042");// TODO add your handling code here:
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
       displayColor.setBackground(new Color(72,61,139));
displayColor.setText("darkslateblue_Ext");
colorName.setText("darkslateblue_Ext");color_code.setText("2043"); // TODO add your handling code here:
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
       displayColor.setBackground(new Color(65,105,225));
displayColor.setText("royalblue_Ext");
colorName.setText("royalblue_Ext"); color_code.setText("2044");// TODO add your handling code here:
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
       displayColor.setBackground(new Color(0,0,255));
displayColor.setText("blue_Ext");
colorName.setText("blue_Extv"); color_code.setText("2045");// TODO add your handling code here:
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
       displayColor.setBackground(new Color(0,0,205));
displayColor.setText("mediumblue_Ext");
colorName.setText("mediumblue_Ext"); color_code.setText("2046");// TODO add your handling code here:
    }//GEN-LAST:event_b6MouseClicked
     
    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
//setting background color
        b1.setBackground(new Color(123,104,238));
b2.setBackground(new Color(106,90,205));
b3.setBackground(new Color(72,61,139));
b4.setBackground(new Color(65,105,225));
b5.setBackground(new Color(0,0,255));
b6.setBackground(new Color(0,0,205));
b7.setBackground(new Color(0,0,139));

//setting visibility
b1.setVisible(true);
b2.setVisible(true);
b3.setVisible(true);

b4.setVisible(true);
b5.setVisible(true);
b6.setVisible(true);
b7.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_blueButtonActionPerformed

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
              displayColor.setBackground(new Color(123,104,238));
displayColor.setText("mediumslateblue_Ext");
colorName.setText("mediumslateblue_Ext");color_code.setText("2041");
        // TODO add your handling code here:
    }//GEN-LAST:event_b1MouseClicked

    private void g2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2MouseClicked
        displayColor.setBackground(new java.awt.Color(127,255,0));
 displayColor.setText(" Green_Ext");
 colorName.setText(" Green_Ext");color_code.setText("2010");
 // TODO add your handling code here:
    }//GEN-LAST:event_g2MouseClicked

    private void g3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3MouseClicked
      displayColor.setBackground(new java.awt.Color(50,205,50));
 displayColor.setText("Lime Green_Ext");color_code.setText("2011");
 colorName.setText("Lime Green_Ext");   // TODO add your handling code here:
    }//GEN-LAST:event_g3MouseClicked

    private void g4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g4MouseClicked
      displayColor.setBackground(new java.awt.Color(0,255,0));
 displayColor.setText("Hunter Green_Ext");
 colorName.setText("Hunter Green_Ext");color_code.setText("2012");   // TODO add your handling code here:
    }//GEN-LAST:event_g4MouseClicked

    private void g5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g5MouseClicked
      displayColor.setBackground(new java.awt.Color(34,139,34));
 displayColor.setText("Forest Green_Ext");
 colorName.setText("Forest Green_Ext"); color_code.setText("2013");  // TODO add your handling code here:
    }//GEN-LAST:event_g5MouseClicked

    private void g6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g6MouseClicked
       displayColor.setBackground(new java.awt.Color(0,128,0));
displayColor.setText("Kelly Green_Ext");
colorName.setText("Kelly Green_Ext");color_code.setText("2014"); // TODO add your handling code here:
    }//GEN-LAST:event_g6MouseClicked

    private void g7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g7MouseClicked
      displayColor.setBackground(new java.awt.Color(0,100,0));
displayColor.setText("Malachite_Ext");
colorName.setText("Malachite_Ext"); color_code.setText("2015"); // TODO add your handling code here:
    }//GEN-LAST:event_g7MouseClicked

    private void g1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked
 displayColor.setBackground(new java.awt.Color(124,252,0));
        displayColor.setText("Grass Green_Ext");
        colorName.setText("Grass Green_Ext"); color_code.setText("2009");       // TODO add your handling code here:
    }//GEN-LAST:event_g1MouseClicked

    private void y2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y2MouseClicked
         displayColor.setBackground(new java.awt.Color(255, 255, 143));
          displayColor.setText(" Canary Yellow_Ext");
          colorName.setText(" Canary Yellow_Ext");color_code.setText("2026"); // TODO add your handling code here:
    }//GEN-LAST:event_y2MouseClicked

    private void y3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y3MouseClicked
                 displayColor.setBackground(new java.awt.Color(228, 208, 10));
 displayColor.setText(" Citrine_Ext");color_code.setText("2027");
colorName.setText(" Citrine_Ext");// TODO add your handling code here:
    }//GEN-LAST:event_y3MouseClicked

    private void y4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y4MouseClicked
             displayColor.setBackground(new java.awt.Color(255, 215, 0));
         displayColor.setText(" Gold_Ext");
colorName.setText(" Gold_Ext");color_code.setText("2028");  // TODO add your handling code here:
    }//GEN-LAST:event_y4MouseClicked

    private void y5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y5MouseClicked
               displayColor.setBackground(new java.awt.Color(255, 192, 0));
 displayColor.setText(" Golden Yellow_Ext");
colorName.setText(" Golden Yellow_Ext");color_code.setText("2029"); // TODO add your handling code here:
    }//GEN-LAST:event_y5MouseClicked

    private void y6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y6MouseClicked
               displayColor.setBackground(new java.awt.Color(255, 250, 160));
         displayColor.setText("Pastel Yellow_Ext");color_code.setText("2030");
colorName.setText("Pastel Yellow_Ext"); // TODO add your handling code here:
    }//GEN-LAST:event_y6MouseClicked

    private void y7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y7MouseClicked
          displayColor.setBackground(new java.awt.Color(255, 255, 0));
         displayColor.setText("Yellow_Ext");color_code.setText("2031");
colorName.setText(" Yellow_Ext"); // TODO add your handling code here:
    }//GEN-LAST:event_y7MouseClicked

    private void gr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr1MouseClicked
       displayColor.setBackground(new Color(237, 234, 222));
          displayColor.setText(" gainsboro_Ext");
          colorName.setText(" gainsboro_Ext"); color_code.setText("2060"); // TODO add your handling code here:
    }//GEN-LAST:event_gr1MouseClicked

    private void w3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w3MouseClicked
      displayColor.setBackground(new Color(255, 255, 240));
           displayColor.setText(" Ivory_Ext");color_code.setText("2051");
colorName.setText(" Ivory_Ext");  // TODO add your handling code here:
    }//GEN-LAST:event_w3MouseClicked

    private void w4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w4MouseClicked
      displayColor.setBackground(new Color(233, 220, 201));
          displayColor.setText(" Linen_Ext");
colorName.setText(" Linen_Ext"); color_code.setText("2052"); // TODO add your handling code here:
    }//GEN-LAST:event_w4MouseClicked

    private void w5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w5MouseClicked
        displayColor.setBackground(new Color(255, 222, 173));
          displayColor.setText("Navajo White_Ext");color_code.setText("2053");
colorName.setText("Navajo White_Ext");// TODO add your handling code here:
    }//GEN-LAST:event_w5MouseClicked

    private void w6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w6MouseClicked
        displayColor.setBackground(new Color(250, 249, 246));
           displayColor.setText(" Off White_Ext");color_code.setText("2054");
colorName.setText(" Off White_Ext"); // TODO add your handling code here:
    }//GEN-LAST:event_w6MouseClicked

    private void w7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w7MouseClicked
         displayColor.setBackground(new Color(252, 245, 229));
           displayColor.setText(" Parchment_Ext");color_code.setText("2055");
colorName.setText(" Parchment_Ext");// TODO add your handling code here:
    }//GEN-LAST:event_w7MouseClicked

    private void w2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w2MouseClicked
         displayColor.setBackground(new Color(249, 246, 238));
            displayColor.setText("Bone White_Ext");color_code.setText("2050");
            colorName.setText("Bone White_Ext");// TODO add your handling code here:
    }//GEN-LAST:event_w2MouseClicked

    private void greenButttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenButttonMouseClicked
//setting backgroud color
g1.setBackground(new Color(124,252,0));  
g2.setBackground(new Color(127,255,0));
g3.setBackground(new Color(50,205,50));
g4.setBackground(new Color(0,255,0));
g5.setBackground(new Color(34,139,34));
g6.setBackground(new Color(0,128,0));
g7.setBackground(new Color(0,100,0));


// setting visibility
g1.setVisible(true);
g2.setVisible(true);
g3.setVisible(true);
g4.setVisible(true);
g5.setVisible(true);
g6.setVisible(true);
g7.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_greenButttonMouseClicked

    private void whiteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteButtonMouseClicked
w1.setBackground(new Color(237, 234, 222));
w2.setBackground(new Color(249, 246, 238));
w3.setBackground(new Color(255, 255, 240));
w4.setBackground(new Color(233, 220, 201));
w5.setBackground(new Color(255, 222, 173));
w6.setBackground(new Color(250, 249, 246));
w7.setBackground(new Color(252, 245, 229));


//visibility
 w1.setVisible(true);
w2.setVisible(true);
w3.setVisible(true);
w4.setVisible(true);
w5.setVisible(true);
w6.setVisible(true);
w7.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_whiteButtonMouseClicked

    private void w1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w1MouseClicked
 displayColor.setBackground(new Color(237, 234, 222));
          displayColor.setText(" Alabaster_Ext");
          colorName.setText(" Alabaster_Ext");    color_code.setText("2049");    // TODO add your handling code here:
    }//GEN-LAST:event_w1MouseClicked

    private void gr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr2MouseClicked
      displayColor.setBackground(new Color(211,211,211));
          displayColor.setText(" Lightgrey_Ext");
          colorName.setText(" Lightgrey_Ext"); color_code.setText("2061");    // TODO add your handling code here:
    }//GEN-LAST:event_gr2MouseClicked

    private void gr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr3MouseClicked
        displayColor.setBackground(new Color(192,192,192));
          displayColor.setText("silver_Ext");
          colorName.setText(" silver_Ext"); color_code.setText("2062"); // TODO add your handling code here:
    }//GEN-LAST:event_gr3MouseClicked

    private void gr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr4MouseClicked
        displayColor.setBackground(new Color(169,169,169));
          displayColor.setText(" darkgrey_Ext");
          colorName.setText("darkgrey_Ext"); color_code.setText("2063"); // TODO add your handling code here:
    }//GEN-LAST:event_gr4MouseClicked

    private void gr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr5MouseClicked
        displayColor.setBackground(new Color(128,128,128));
          displayColor.setText("gray_Ext");
          colorName.setText("gray_Ext");color_code.setText("2064");  // TODO add your handling code here:
    }//GEN-LAST:event_gr5MouseClicked

    private void gr6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr6MouseClicked
        displayColor.setBackground(new Color(105,105,105));
          displayColor.setText(" dimgrey_Ext");
          colorName.setText("  dimgrey_Ext");color_code.setText("2065");  // TODO add your handling code here:
    }//GEN-LAST:event_gr6MouseClicked

    private void gr7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gr7MouseClicked
        displayColor.setBackground(new Color(119,136,153));
          displayColor.setText("lightslategrey_Ext");
          colorName.setText("lightslategrey_Ext");color_code.setText("2066");  // TODO add your handling code here:
    }//GEN-LAST:event_gr7MouseClicked

    private void grayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grayButtonMouseClicked
gr1.setBackground(new Color(220,220,220));
gr2.setBackground(new Color(211,211,211));
gr3.setBackground(new Color(192,192,192));
gr4.setBackground(new Color(169,169,169));
gr5.setBackground(new Color(128,128,128));
gr6.setBackground(new Color(105,105,105));
gr7.setBackground(new Color(119,136,153));


//visibility
 gr1.setVisible(true);
gr2.setVisible(true);
gr3.setVisible(true);
gr4.setVisible(true);
gr5.setVisible(true);
gr6.setVisible(true);
gr7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_grayButtonMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
Menu m=new Menu();
m.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
DealerLogin d= new DealerLogin();
          String code=color_code.getText();
          String Cquantity=(String)color_quantity.getSelectedItem();
          System.out.println(Cquantity);
       
        if(!code.isEmpty() && code!="none" ){
       System.out.println("Code"+code);
     
        int quantity=Integer.parseInt(Cquantity);
        
        int orderId=d.order_id;
   
        try{ MysqlConnectionProvider p=new MysqlConnectionProvider();
        p.insertIntoOrderTable(orderId, code,quantity);
            System.out.println("data Inserted");
             addedToBill a=new addedToBill();
            a.setVisible(true);
       }catch(Exception e){
            System.out.println(e);
       }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Please Select product");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exterior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exterior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exterior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exterior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exterior().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel bg_image;
    private javax.swing.JButton blueButton;
    private javax.swing.JLabel colorName;
    private javax.swing.JLabel color_code;
    private javax.swing.JComboBox<String> color_quantity;
    private javax.swing.JLabel displayColor;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel gr1;
    private javax.swing.JLabel gr2;
    private javax.swing.JLabel gr3;
    private javax.swing.JLabel gr4;
    private javax.swing.JLabel gr5;
    private javax.swing.JLabel gr6;
    private javax.swing.JLabel gr7;
    private javax.swing.JButton grayButton;
    private javax.swing.JButton greenButtton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel r5;
    private javax.swing.JLabel r6;
    private javax.swing.JLabel r7;
    private javax.swing.JButton redButton;
    private javax.swing.JLabel w1;
    private javax.swing.JLabel w2;
    private javax.swing.JLabel w3;
    private javax.swing.JLabel w4;
    private javax.swing.JLabel w5;
    private javax.swing.JLabel w6;
    private javax.swing.JLabel w7;
    private javax.swing.JButton whiteButton;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    private javax.swing.JLabel y3;
    private javax.swing.JLabel y4;
    private javax.swing.JLabel y5;
    private javax.swing.JLabel y6;
    private javax.swing.JLabel y7;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables

    private void hideColors() {
 //RED SHADES DISABLED
        r1.setVisible(false);
        r2.setVisible(false);
        r3.setVisible(false);
        r4.setVisible(false);
        r5.setVisible(false);
        r6.setVisible(false);
        r7.setVisible(false);
            //BULE SHADES DISABLE
 
b1.setVisible(false);
b2.setVisible(false);
b3.setVisible(false);

b4.setVisible(false);
b5.setVisible(false);
b6.setVisible(false);
b7.setVisible(false);
//green
g1.setVisible(false);
g2.setVisible(false);
g3.setVisible(false);

g4.setVisible(false);
g5.setVisible(false);
g6.setVisible(false);
g7.setVisible(false);

//YELLOW
y1.setVisible(false);

        y2.setVisible(false);

        y3.setVisible(false);

        y4.setVisible(false);

        y5.setVisible(false);

        y6.setVisible(false);

        y7.setVisible(false);
        //white
  w1.setVisible(false);
w2.setVisible(false);
w3.setVisible(false);
w4.setVisible(false);
w5.setVisible(false);
w6.setVisible(false);
w7.setVisible(false);

        //gray
gr1.setVisible(false);
gr2.setVisible(false);
gr3.setVisible(false);

gr4.setVisible(false);
gr5.setVisible(false);
gr6.setVisible(false);
gr7.setVisible(false);


    }

   private void resizing_defaultImage() {
       
       ImageIcon icon=new ImageIcon((getClass().getResource("/exterior/ext222.jpg"))); 
       Image img =icon.getImage();
       Image imageScale = img.getScaledInstance(bg_image.getWidth(),bg_image.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon scaledIcon=new ImageIcon(imageScale);
     bg_image.setIcon(scaledIcon);
      
    }
    }

