/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interior;

import DealerLoginForm.DealerLogin;
import HomeMenu.Menu;
import added.addedToBill;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdbc.MysqlConnectionProvider;

/**
 *
 * @author mahen
 */
public class Interior extends javax.swing.JFrame {

    /**
     * Creates new form adi22
     */
    public Interior() {
        initComponents();
        hide_visibility();
      
        resize_imageDeafult();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        redButton = new javax.swing.JButton();
        buleButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        pinkButton = new javax.swing.JButton();
        purpleButton = new javax.swing.JButton();
        color_display = new java.awt.Label();
        label3 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        color_Price = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        color_code = new javax.swing.JLabel();
        color_Name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        color_qnty = new javax.swing.JComboBox<>();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        l1 = new java.awt.Label();
        l2 = new java.awt.Label();
        l3 = new java.awt.Label();
        l4 = new java.awt.Label();
        l5 = new java.awt.Label();
        l6 = new java.awt.Label();
        l7 = new java.awt.Label();
        l8 = new java.awt.Label();
        a11 = new java.awt.Label();
        a12 = new java.awt.Label();
        a13 = new java.awt.Label();
        a14 = new java.awt.Label();
        a15 = new java.awt.Label();
        a16 = new java.awt.Label();
        a17 = new java.awt.Label();
        a18 = new java.awt.Label();
        l25 = new java.awt.Label();
        l26 = new java.awt.Label();
        l27 = new java.awt.Label();
        l28 = new java.awt.Label();
        l29 = new java.awt.Label();
        l30 = new java.awt.Label();
        l31 = new java.awt.Label();
        l32 = new java.awt.Label();
        l33 = new java.awt.Label();
        l34 = new java.awt.Label();
        l35 = new java.awt.Label();
        l36 = new java.awt.Label();
        l37 = new java.awt.Label();
        l38 = new java.awt.Label();
        l39 = new java.awt.Label();
        l40 = new java.awt.Label();
        l41 = new java.awt.Label();
        l42 = new java.awt.Label();
        l43 = new java.awt.Label();
        l44 = new java.awt.Label();
        l45 = new java.awt.Label();
        l46 = new java.awt.Label();
        l47 = new java.awt.Label();
        l48 = new java.awt.Label();
        l49 = new java.awt.Label();
        l50 = new java.awt.Label();
        l51 = new java.awt.Label();
        l52 = new java.awt.Label();
        l53 = new java.awt.Label();
        l54 = new java.awt.Label();
        l55 = new java.awt.Label();
        l56 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        jButton9 = new javax.swing.JButton();
        color_name = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interior Paints");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redButton.setBackground(new java.awt.Color(255, 0, 0));
        redButton.setText("Red");
        redButton.setBorder(null);
        redButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redButtonMouseClicked(evt);
            }
        });
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        getContentPane().add(redButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 94, 42));

        buleButton.setBackground(new java.awt.Color(0, 0, 255));
        buleButton.setText("Blue");
        buleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 89, 39));

        greenButton.setBackground(new java.awt.Color(0, 128, 0));
        greenButton.setText("Green");
        greenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenButtonMouseClicked(evt);
            }
        });
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(greenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 91, 41));

        yellowButton.setBackground(new java.awt.Color(255, 255, 51));
        yellowButton.setText("Yellow");
        yellowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowButtonMouseClicked(evt);
            }
        });
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yellowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 97, 41));

        whiteButton.setBackground(new java.awt.Color(255, 255, 255));
        whiteButton.setText("White");
        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(whiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 91, 41));

        pinkButton.setBackground(new java.awt.Color(255, 51, 204));
        pinkButton.setText("Pink");
        pinkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinkButtonMouseClicked(evt);
            }
        });
        pinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pinkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 91, 40));

        purpleButton.setBackground(new java.awt.Color(153, 0, 153));
        purpleButton.setText("Purple");
        purpleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleButtonMouseClicked(evt);
            }
        });
        purpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(purpleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 82, 41));

        color_display.setAlignment(java.awt.Label.CENTER);
        color_display.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(color_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 280, 341));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 0, 0));
        label3.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("sample colour");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 280, 64));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COLOR CODE :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 12, 136, 34);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COLOR NAME:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 150, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRICE PER Liter:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 10, 170, 34);

        color_Price.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        color_Price.setForeground(new java.awt.Color(255, 255, 255));
        color_Price.setText("jLabel5");
        jPanel1.add(color_Price);
        color_Price.setBounds(500, 10, 110, 34);

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROYALE", "APCOLITE", "TRACTOR", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(520, 90, 190, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COLOR QUALITY:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 80, 157, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COLOR QUANTITY:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 10, 180, 34);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("in  Ltr");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(930, 10, 62, 40);

        color_code.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        color_code.setForeground(new java.awt.Color(255, 255, 255));
        color_code.setText("none");
        jPanel1.add(color_code);
        color_code.setBounds(160, 10, 99, 34);

        color_Name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        color_Name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(color_Name);
        color_Name.setBounds(160, 80, 180, 36);

        jLabel11.setBackground(new java.awt.Color(255, 255, 153));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interior/icons8_shopping_cart_48px_1.png"))); // NOI18N
        jLabel11.setText("ADD TO BILL");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(840, 70, 160, 54);

        color_qnty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        color_qnty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "10", "15" }));
        jPanel1.add(color_qnty);
        color_qnty.setBounds(810, 10, 110, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1020, 130));

        label5.setPreferredSize(new java.awt.Dimension(50, 50));
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 55, 42));

        label7.setPreferredSize(new java.awt.Dimension(30, 30));
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
        });
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 55, 42));

        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
        });
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 55, 42));

        label9.setPreferredSize(new java.awt.Dimension(30, 30));
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label9MouseClicked(evt);
            }
        });
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 55, 42));

        label10.setPreferredSize(new java.awt.Dimension(30, 30));
        label10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label10MouseClicked(evt);
            }
        });
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 55, 42));

        label11.setPreferredSize(new java.awt.Dimension(30, 30));
        label11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label11MouseClicked(evt);
            }
        });
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 55, 42));

        label12.setPreferredSize(new java.awt.Dimension(30, 30));
        label12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label12MousePressed(evt);
            }
        });
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 55, 42));

        label13.setPreferredSize(new java.awt.Dimension(30, 30));
        label13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label13MouseEntered(evt);
            }
        });
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 55, 42));

        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 55, 40));

        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 55, 42));

        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 55, 42));

        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 55, 42));

        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 55, 42));

        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 55, 42));

        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 55, 42));

        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 55, 42));

        a11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a11MouseEntered(evt);
            }
        });
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 55, 42));

        a12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a12MouseClicked(evt);
            }
        });
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 55, 42));

        a13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a13MouseClicked(evt);
            }
        });
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 55, 42));

        a14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a14MouseClicked(evt);
            }
        });
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 55, 42));

        a15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a15MouseClicked(evt);
            }
        });
        getContentPane().add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 55, 42));

        a16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a16MouseClicked(evt);
            }
        });
        getContentPane().add(a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 55, 42));

        a17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a17MouseClicked(evt);
            }
        });
        getContentPane().add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 55, 42));

        a18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a18MouseClicked(evt);
            }
        });
        getContentPane().add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 55, 42));

        l25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l25MouseClicked(evt);
            }
        });
        getContentPane().add(l25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 55, 42));

        l26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l26MouseClicked(evt);
            }
        });
        getContentPane().add(l26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 55, 42));

        l27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l27MouseClicked(evt);
            }
        });
        getContentPane().add(l27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 55, 42));

        l28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l28MouseClicked(evt);
            }
        });
        getContentPane().add(l28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 55, 42));

        l29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l29MouseClicked(evt);
            }
        });
        getContentPane().add(l29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 55, 42));

        l30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l30MouseClicked(evt);
            }
        });
        getContentPane().add(l30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 55, 42));

        l31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l31MouseClicked(evt);
            }
        });
        getContentPane().add(l31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 55, 42));

        l32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l32MouseClicked(evt);
            }
        });
        getContentPane().add(l32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 55, 42));

        l33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l33MouseClicked(evt);
            }
        });
        getContentPane().add(l33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 55, 42));

        l34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l34MouseClicked(evt);
            }
        });
        getContentPane().add(l34, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 55, 42));

        l35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l35MouseClicked(evt);
            }
        });
        getContentPane().add(l35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 55, 42));

        l36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l36MouseClicked(evt);
            }
        });
        getContentPane().add(l36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 55, 42));

        l37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l37MouseClicked(evt);
            }
        });
        getContentPane().add(l37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 55, 42));

        l38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l38MouseClicked(evt);
            }
        });
        getContentPane().add(l38, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 55, 42));

        l39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l39MouseClicked(evt);
            }
        });
        getContentPane().add(l39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 55, 42));

        l40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l40MouseClicked(evt);
            }
        });
        getContentPane().add(l40, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 55, 42));

        l41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l41MouseClicked(evt);
            }
        });
        getContentPane().add(l41, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 55, 42));

        l42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l42MouseClicked(evt);
            }
        });
        getContentPane().add(l42, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 55, 42));

        l43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l43MouseClicked(evt);
            }
        });
        getContentPane().add(l43, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 55, 42));

        l44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l44MouseClicked(evt);
            }
        });
        getContentPane().add(l44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 55, 42));

        l45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l45MouseClicked(evt);
            }
        });
        getContentPane().add(l45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 55, 42));

        l46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l46MouseClicked(evt);
            }
        });
        getContentPane().add(l46, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 55, 42));

        l47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l47MouseClicked(evt);
            }
        });
        getContentPane().add(l47, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 55, 42));

        l48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l48MouseClicked(evt);
            }
        });
        getContentPane().add(l48, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 55, 42));

        l49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l49MouseClicked(evt);
            }
        });
        getContentPane().add(l49, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 55, 42));

        l50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l50MouseClicked(evt);
            }
        });
        getContentPane().add(l50, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 55, 42));

        l51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l51MouseClicked(evt);
            }
        });
        getContentPane().add(l51, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 55, 42));

        l52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l52MouseClicked(evt);
            }
        });
        getContentPane().add(l52, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 55, 42));

        l53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l53MouseClicked(evt);
            }
        });
        getContentPane().add(l53, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 55, 42));

        l54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l54MouseClicked(evt);
            }
        });
        getContentPane().add(l54, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 55, 42));

        l55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l55MouseClicked(evt);
            }
        });
        getContentPane().add(l55, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 55, 42));

        l56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l56MouseClicked(evt);
            }
        });
        getContentPane().add(l56, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, 55, 42));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label4.setText("N");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 102, 76));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label6.setText("I");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 102, 76));

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label14.setText("T");
        jPanel2.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 102, 76));

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label15.setText("E");
        jPanel2.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, 102, 76));

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label16.setText("R");
        jPanel2.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 354, 102, 76));

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label17.setText("R");
        jPanel2.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 612, 102, 76));

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label18.setText("I");
        jPanel2.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 102, 76));

        label19.setAlignment(java.awt.Label.CENTER);
        label19.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        label19.setText("O");
        jPanel2.add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 526, 102, 76));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        jButton9.setBackground(new java.awt.Color(0, 255, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interior/icons8_back_arrow_26px.png"))); // NOI18N
        jButton9.setText("Back");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 110, -1));

        color_name.setBackground(new java.awt.Color(255, 255, 255));
        color_name.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        color_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        color_name.setOpaque(true);
        getContentPane().add(color_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 280, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interior/int2.jpg"))); // NOI18N
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 136, 1020, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redButtonMouseClicked
//label5.setBackground(Color.red);     

     //SET BACKGROUND  
label5.setBackground(new Color(250,128,114));
//label6.setBackground(new Color(255,0,0));
label8.setBackground(new Color(255,160,122));
label10.setBackground(new Color(233,150,122));
label7.setBackground(new Color(240,128,128));
label11.setBackground(new Color(205,92,92));
label12.setBackground(new Color(220,20,60));
label9.setBackground(new Color(178,34,34));
label13.setBackground(new Color(255,0,0));
//SET VISIBILITY
 label8.setVisible(true);
        label5.setVisible(true);
        label10.setVisible(true);
        label7.setVisible(true);
        label11.setVisible(true);
        label12.setVisible(true);
        label9.setVisible(true);
        label13.setVisible(true);



// TODO add your handling code here:
    }//GEN-LAST:event_redButtonMouseClicked

    private void pinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkButtonActionPerformed
l41.setBackground(new Color(170, 51, 106));
l42.setBackground(new Color(255, 182, 193));
l43.setBackground(new Color(222, 49, 99));
l44.setBackground(new Color(248, 131, 121));
l45.setBackground(new Color(220, 20, 60));
l46.setBackground(new Color(170, 51, 106));
l47.setBackground(new Color(55, 105, 180));
l48.setBackground(new Color(255, 192, 203));
//visibility
l41.setVisible(true);
l42.setVisible(true);
l43.setVisible(true);
l44.setVisible(true);
l45.setVisible(true);
l46.setVisible(true);
l47.setVisible(true);
l48.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_pinkButtonActionPerformed

    private void buleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buleButtonActionPerformed
//setting background color
        l1.setBackground(new Color(123,104,238));
l2.setBackground(new Color(106,90,205));
l3.setBackground(new Color(72,61,139));
l4.setBackground(new Color(65,105,225));
l5.setBackground(new Color(0,0,255));
l6.setBackground(new Color(0,0,205));
l7.setBackground(new Color(0,0,139));
l8.setBackground(new Color(0,0,128));  
//setting visibility
l1.setVisible(true);
l2.setVisible(true);
l3.setVisible(true);

l4.setVisible(true);
l5.setVisible(true);
l6.setVisible(true);
l7.setVisible(true);
l8 .setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_buleButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
//setting backgroud color
a11.setBackground(new Color(124,252,0));  
a12.setBackground(new Color(127,255,0));
a13.setBackground(new Color(50,205,50));
a14.setBackground(new Color(0,255,0));
a15.setBackground(new Color(34,139,34));
a16.setBackground(new Color(0,128,0));
a17.setBackground(new Color(0,100,0));
a18.setBackground(new Color(173,255,47));

// setting visibility
a11.setVisible(true);
a12.setVisible(true);
a13.setVisible(true);
a14.setVisible(true);
a15.setVisible(true);
a16.setVisible(true);
a17.setVisible(true);
a18.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_greenButtonActionPerformed

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked
color_display.setBackground(new Color(250,128,114)); 
color_name.setText("Salmon");
color_Name.setText("Salmon");
color_code.setText("1000");

// TODO add your handling code here:
    }//GEN-LAST:event_label8MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
color_display.setBackground(new Color(255,160,122));  
color_name.setText("lightsalmon");
color_Name.setText("lightsalmon");
color_code.setText("1001");
// TODO add your handling code here:
    }//GEN-LAST:event_label5MouseClicked

    private void label10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseClicked
color_display.setBackground(new Color(233,150,122));        // TODO add your handling code here:
color_name.setText("darksalmon");
color_Name.setText("darksalmon");color_code.setText("1002");
    }//GEN-LAST:event_label10MouseClicked

    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked
color_display.setBackground(new Color(240,128,128));        // TODO add your handling code here:
color_name.setText("lightcoral");
color_Name.setText("lightcoral");color_code.setText("1003");
    }//GEN-LAST:event_label7MouseClicked

    private void label11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label11MouseClicked
color_display.setBackground(new Color(205,92,92));
color_name.setText("indianred");
color_Name.setText("indianred");
color_code.setText("1004");
       // TODO add your handling code here:
    }//GEN-LAST:event_label11MouseClicked

    private void label12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MousePressed
color_display.setBackground(new Color(220,20,60));
color_name.setText("crimson");
color_Name.setText("crimson");color_code.setText("1005");
       // TODO add your handling code here:
    }//GEN-LAST:event_label12MousePressed

    private void label13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label13MouseEntered

    private void label13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label13MouseClicked
color_display.setBackground(new Color(178,34,34));
color_name.setText("firebrick");
color_Name.setText("firebrick");color_code.setText("1006");
       // TODO add your handling code here:
    }//GEN-LAST:event_label13MouseClicked

    private void label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseClicked
color_name.setText("red");
color_Name.setText("red");
color_code.setText("1007");
        color_display.setBackground(new Color(255,0,0));           // TODO add your handling code here:
    }//GEN-LAST:event_label9MouseClicked

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_redButtonActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
color_display.setBackground(new Color(123,104,238));
color_name.setText("mediumslateblue");
color_Name.setText("mediumslateblue");color_code.setText("1041");
         // TODO add your handling code here:
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
color_display.setBackground(new Color(106,90,205));
color_name.setText("slateblue");
color_Name.setText("slateblue");color_code.setText("1042");
      // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
color_display.setBackground(new Color(72,61,139));
color_name.setText("darkslateblue");
color_Name.setText("darkslateblue");color_code.setText("1043");
         // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
color_display.setBackground(new Color(65,105,225));
color_name.setText("royalblue");
color_Name.setText("royalblue");color_code.setText("1044");
         // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
color_display.setBackground(new Color(0,0,255));
color_name.setText("blue");
color_Name.setText("blue");color_code.setText("1045");
      // TODO add your handling code here:
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
color_display.setBackground(new Color(0,0,205));
color_name.setText("mediumblue");
color_Name.setText("mediumblue");color_code.setText("1046");
        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
color_display.setBackground(new Color(0,0,139));
color_name.setText("darkblue");
color_Name.setText("darkblue");color_code.setText("1047");
       // TODO add your handling code here:
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
color_display.setBackground(new Color(0,0,128));   
color_name.setText("navy");
color_Name.setText("navy");color_code.setText("1048");
// TODO add your handling code here:
    }//GEN-LAST:event_l8MouseClicked

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void yellowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowButtonMouseClicked
//settting background color
        l25.setBackground(new java.awt.Color(225, 193, 110));

        l26.setBackground(new java.awt.Color(255, 255, 143));

        l27.setBackground(new java.awt.Color(228, 208, 10));

        l28.setBackground(new java.awt.Color(255, 215, 0));

        l29.setBackground(new java.awt.Color(255, 192, 0));

        l30.setBackground(new java.awt.Color(255, 250, 160));

        l31.setBackground(new java.awt.Color(255, 255, 0));

        l32.setBackground(new java.awt.Color(255, 170, 51));    
        //set visibility
        l25.setVisible(true);

        l26.setVisible(true);

        l27.setVisible(true);

        l28.setVisible(true);

        l29.setVisible(true);

        l30.setVisible(true);

        l31.setVisible(true);

        l32.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_yellowButtonMouseClicked

    private void greenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_greenButtonMouseClicked

    private void a11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a11MouseClicked
        color_display.setBackground(new java.awt.Color(124,252,0));
        color_name.setText("Grass Green");
        color_Name.setText("Grass Green");
        color_code.setText("1009");
        

                // TODO add your handling code here:
    }//GEN-LAST:event_a11MouseClicked

    private void a12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a12MouseClicked
 color_display.setBackground(new java.awt.Color(127,255,0));
 color_name.setText(" Green");
 color_Name.setText(" Green");
color_code.setText("1010");
              // TODO add your handling code here:
    }//GEN-LAST:event_a12MouseClicked

    private void a13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a13MouseClicked
 color_display.setBackground(new java.awt.Color(50,205,50));
 color_name.setText("Lime Green");
 color_Name.setText("Lime Green");
 color_code.setText("1011");

               // TODO add your handling code here:
    }//GEN-LAST:event_a13MouseClicked

    private void a14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a14MouseClicked
 color_display.setBackground(new java.awt.Color(0,255,0));
 color_name.setText("Hunter Green");
 color_Name.setText("Hunter Green");
color_code.setText("1012");
               // TODO add your handling code here:
    }//GEN-LAST:event_a14MouseClicked

    private void a15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a15MouseClicked
 color_display.setBackground(new java.awt.Color(34,139,34));
 color_name.setText("Forest Green");
 color_Name.setText("Forest Green");
 color_code.setText("1013");

              // TODO add your handling code here:
    }//GEN-LAST:event_a15MouseClicked

    private void a16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a16MouseClicked
color_display.setBackground(new java.awt.Color(0,128,0));
color_name.setText("Kelly Green");
color_Name.setText("Kelly Green");
color_code.setText("1014");
                   // TODO add your handling code here:
    }//GEN-LAST:event_a16MouseClicked

    private void a17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a17MouseClicked
color_display.setBackground(new java.awt.Color(0,100,0));
color_name.setText("Malachite");
color_Name.setText("Malachite");
color_code.setText("1015");
// TODO add your handling code here:
    }//GEN-LAST:event_a17MouseClicked

    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteButtonActionPerformed
l33.setBackground(new Color(237, 234, 222));
l34.setBackground(new Color(249, 246, 238));
l35.setBackground(new Color(255, 255, 240));
l36.setBackground(new Color(233, 220, 201));
l37.setBackground(new Color(255, 222, 173));
l38.setBackground(new Color(250, 249, 246));
l39.setBackground(new Color(252, 245, 229));
l40.setBackground(new Color(255, 255, 255));

//visibility
 l33.setVisible(true);
l34.setVisible(true);
l35.setVisible(true);
l36.setVisible(true);
l37.setVisible(true);
l38.setVisible(true);
l39.setVisible(true);
l40.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_whiteButtonActionPerformed

    private void purpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleButtonActionPerformed
l49.setBackground(new Color(128, 0, 128));
l50.setBackground(new Color(48, 25, 52));
l51.setBackground(new Color(72, 50, 72));
l52.setBackground(new Color(230, 230, 250));
l53.setBackground(new Color(203, 195, 227));
l54.setBackground(new Color(207, 159, 255));
l55.setBackground(new Color(195, 177, 225));
l56.setBackground(new Color(216, 191, 216));
//visibility

        // TODO add your handling code here:
    }//GEN-LAST:event_purpleButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void a11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a11MouseEntered

    private void a18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a18MouseClicked
        // TODO add your handling code here:
        color_display.setBackground(new Color(173,255,47));
        color_name.setText("Mint Green");
        color_Name.setText("Mint Green");
        color_code.setText("1016");
    }//GEN-LAST:event_a18MouseClicked

    private void l25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l25MouseClicked
        // TODO add your handling code here:
        color_display.setBackground(new java.awt.Color(225, 193, 110));
         color_name.setText(" Brass");
         color_Name.setText(" Brass");
         color_code.setText("1025");
    }//GEN-LAST:event_l25MouseClicked

    private void l26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l26MouseClicked
        // TODO add your handling code here:
         color_display.setBackground(new java.awt.Color(255, 255, 143));
          color_name.setText(" Canary Yellow");
          color_Name.setText(" Canary Yellow");
          color_code.setText("1026");
    }//GEN-LAST:event_l26MouseClicked

    private void l27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l27MouseClicked
         color_display.setBackground(new java.awt.Color(228, 208, 10));
 color_name.setText(" Citrine");
color_Name.setText(" Citrine");
color_code.setText("1027");
// TODO add your handling code here:
    }//GEN-LAST:event_l27MouseClicked

    private void l28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l28MouseClicked
        color_display.setBackground(new java.awt.Color(255, 215, 0));
         color_name.setText(" Gold");
color_Name.setText(" Gold");
color_code.setText("1028");
// TODO add your handling code here:
    }//GEN-LAST:event_l28MouseClicked

    private void l29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l29MouseClicked
        color_display.setBackground(new java.awt.Color(255, 192, 0));
 color_name.setText(" Golden Yellow");
color_Name.setText(" Golden Yellow");
color_code.setText("1029");
// TODO add your handling code here:
    }//GEN-LAST:event_l29MouseClicked

    private void l30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l30MouseClicked
        color_display.setBackground(new java.awt.Color(255, 250, 160));
         color_name.setText("Pastel Yellow");
color_Name.setText("Pastel Yellow");
color_code.setText("1030");
// TODO add your handling code here:
    }//GEN-LAST:event_l30MouseClicked

    private void l31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l31MouseClicked
        color_display.setBackground(new java.awt.Color(255, 255, 0));
         color_name.setText(" Yellow");
color_Name.setText(" Yellow");color_code.setText("1031");
// TODO add your handling code here:
    }//GEN-LAST:event_l31MouseClicked

    private void l32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l32MouseClicked
        color_display.setBackground(new java.awt.Color(255, 170, 51)); 
 color_name.setText("Yellow Orange");
color_Name.setText("Yellow Orange");
color_code.setText("1032");
// TODO add your handling code here:
    }//GEN-LAST:event_l32MouseClicked

    private void l33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l33MouseClicked
        // TODO add your handling code here:
        color_display.setBackground(new Color(237, 234, 222));
          color_name.setText(" Alabaster");
          color_Name.setText(" Alabaster");
          color_code.setText("1049");
    }//GEN-LAST:event_l33MouseClicked

    private void l34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l34MouseClicked
        // TODO add your handling code here:
          color_display.setBackground(new Color(249, 246, 238));
            color_name.setText("Bone White");
            color_Name.setText("Bone White");
            color_code.setText("1050");
    }//GEN-LAST:event_l34MouseClicked

    private void l35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l35MouseClicked
         color_display.setBackground(new Color(255, 255, 240));
           color_name.setText(" Ivory");
color_Name.setText(" Ivory");color_code.setText("1051");
// TODO add your handling code here:
    }//GEN-LAST:event_l35MouseClicked

    private void l36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l36MouseClicked
        color_display.setBackground(new Color(233, 220, 201));
          color_name.setText(" Linen");
color_Name.setText(" Linen");color_code.setText("1052");
// TODO add your handling code here:
    }//GEN-LAST:event_l36MouseClicked

    private void l37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l37MouseClicked
        color_display.setBackground(new Color(255, 222, 173));
          color_name.setText("Navajo White");
color_Name.setText("Navajo White");color_code.setText("1053");
// TODO add your handling code here:
    }//GEN-LAST:event_l37MouseClicked

    private void l38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l38MouseClicked
         color_display.setBackground(new Color(250, 249, 246));
           color_name.setText(" Off White");
color_Name.setText(" Off White");color_code.setText("1054");
// TODO add your handling code here:
    }//GEN-LAST:event_l38MouseClicked

    private void l39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l39MouseClicked
         color_display.setBackground(new Color(252, 245, 229));
           color_name.setText(" Parchment");
color_Name.setText(" Parchment");color_code.setText("1055");
// TODO add your handling code here:
    }//GEN-LAST:event_l39MouseClicked

    private void l40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l40MouseClicked
         color_display.setBackground(new Color(255, 255, 255));
           color_name.setText(" White");color_code.setText("1056");
color_Name.setText(" White");
// TODO add your handling code here:
    }//GEN-LAST:event_l40MouseClicked

    private void l41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l41MouseClicked
    color_display.setBackground(new Color(170, 51, 106));
    color_name.setText(" Dark Pink");
    color_Name.setText(" Dark Pink");color_code.setText("1033");
    // TODO add your handling code here:
    }//GEN-LAST:event_l41MouseClicked

    private void l42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l42MouseClicked
        color_display.setBackground(new Color(255, 182, 193));
        color_name.setText(" Light Pink");
color_Name.setText(" Light Pink");color_code.setText("1034");
// TODO add your handling code here:
    }//GEN-LAST:event_l42MouseClicked

    private void l43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l43MouseClicked
        color_display.setBackground(new Color(222, 49, 99)); 
        color_name.setText("Cerise");
color_Name.setText("Cerise");color_code.setText("1035");
// TODO add your handling code here:
    }//GEN-LAST:event_l43MouseClicked

    private void l44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l44MouseClicked
       color_display.setBackground(new Color(248, 131, 121));  
       color_name.setText(" Coral Pink");
color_Name.setText(" Coral Pink");color_code.setText("1036");
// TODO add your handling code here:
    }//GEN-LAST:event_l44MouseClicked

    private void l45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l45MouseClicked
       color_display.setBackground(new Color(220, 20, 60)); color_name.setText(" Crimson"); 
color_Name.setText(" Crimson");    color_code.setText("1037");    
// TODO add your handling code here:
    }//GEN-LAST:event_l45MouseClicked

    private void l46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l46MouseClicked
      color_display.setBackground(new Color(170, 51, 106));
      color_name.setText(" Dark Pink");
color_Name.setText(" Dark Pink");color_code.setText("1038");
// TODO add your handling code here:
    }//GEN-LAST:event_l46MouseClicked

    private void l47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l47MouseClicked
        color_display.setBackground(new Color(55, 105, 180));
        color_name.setText(" Mulberry");
color_Name.setText(" Mulberry");color_code.setText("1039");
// TODO add your handling code here:
    }//GEN-LAST:event_l47MouseClicked

    private void l48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l48MouseClicked
       color_display.setBackground(new Color(255, 192, 203)); 
       color_name.setText(" Pastel Red");
color_Name.setText(" Pastel Red");color_code.setText("1040");
// TODO add your handling code here:
    }//GEN-LAST:event_l48MouseClicked

    private void purpleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleButtonMouseClicked
        // TODO add your handling code here:
        l49.setBackground(new Color(170, 51, 106));
l50.setBackground(new Color(48, 25, 52));
l51.setBackground(new Color(72, 50, 72));
l52.setBackground(new Color(230, 230, 250));
l53.setBackground(new Color(203, 195, 227));
l54.setBackground(new Color(207, 159, 255));
l55.setBackground(new Color(195, 177, 225));
l56.setBackground(new Color(216, 191, 216));

//visibillity
l49.setVisible(true);
l50.setVisible(true);
l51.setVisible(true);
l52.setVisible(true);
l53.setVisible(true);
l54.setVisible(true);
l55.setVisible(true);
l56.setVisible(true);

    }//GEN-LAST:event_purpleButtonMouseClicked

    private void l49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l49MouseClicked
       color_display.setBackground(new Color(128, 0, 128));
           color_name.setText("Purple");
color_Name.setText("Purple");color_code.setText("1017");
// TODO add your handling code here:
    }//GEN-LAST:event_l49MouseClicked

    private void l50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l50MouseClicked
        color_display.setBackground(new Color(48, 25, 52));
            color_name.setText("Dark Purple");
color_Name.setText("Dark Purple");color_code.setText("1018");
// TODO add your handling code here:
    }//GEN-LAST:event_l50MouseClicked

    private void l51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l51MouseClicked
        color_display.setBackground(new Color(72, 50, 72));
            color_name.setText(" Eggplant");
color_Name.setText(" Eggplant");color_code.setText("1019");
// TODO add your handling code here:
    }//GEN-LAST:event_l51MouseClicked

    private void l52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l52MouseClicked
        color_display.setBackground(new Color(230, 230, 250));
    color_name.setText(" Lavender");
color_Name.setText(" Lavender");color_code.setText("1020");
// TODO add your handling code here:
    }//GEN-LAST:event_l52MouseClicked

    private void l53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l53MouseClicked
        color_display.setBackground(new Color(203, 195, 227));
            color_name.setText("Light Purple");
color_Name.setText("Light Purple");color_code.setText("1021");
// TODO add your handling code here:
    }//GEN-LAST:event_l53MouseClicked

    private void l54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l54MouseClicked
        color_display.setBackground(new Color(207, 159, 255)); 
    color_name.setText(" Light Violet");
color_Name.setText(" Light Violet");color_code.setText("1022");
// TODO add your handling code here:
    }//GEN-LAST:event_l54MouseClicked

    private void l55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l55MouseClicked
       color_display.setBackground(new Color(195, 177, 225)); 
           color_name.setText("Wine");
color_Name.setText("Wine");color_code.setText("1023");
// TODO add your handling code here:
    }//GEN-LAST:event_l55MouseClicked

    private void l56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l56MouseClicked
         color_display.setBackground(new Color(216, 191, 216));
    color_name.setText(" Thistle");
color_Name.setText(" Thistle");color_code.setText("1024");
// TODO add your handling code here:
    }//GEN-LAST:event_l56MouseClicked

    private void pinkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinkButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pinkButtonMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
Menu m=new Menu();
m.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        DealerLogin d=new DealerLogin();
          String code=color_code.getText();
          String Cquantity=(String)color_qnty.getSelectedItem();
          System.out.println(Cquantity);
          System.out.println("Code"+code);
        if(!code.isEmpty() && code!="none" ){
       System.out.println("Code"+code);
       
        int quantity=Integer.parseInt(Cquantity);
        
        int orderId=d.order_id;
   
        try{ MysqlConnectionProvider p=new MysqlConnectionProvider();
        p.insertIntoOrderTable(orderId, code,quantity);
            System.out.println("data Inserted");
             addedToBill a=new addedToBill();
            a.setVisible(true);
       }catch(Exception e){
            System.out.println(e);
       }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Please Select product");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interior().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label a11;
    private java.awt.Label a12;
    private java.awt.Label a13;
    private java.awt.Label a14;
    private java.awt.Label a15;
    private java.awt.Label a16;
    private java.awt.Label a17;
    private java.awt.Label a18;
    private javax.swing.JButton buleButton;
    private javax.swing.JLabel color_Name;
    private javax.swing.JLabel color_Price;
    private javax.swing.JLabel color_code;
    private java.awt.Label color_display;
    private javax.swing.JLabel color_name;
    private javax.swing.JComboBox<String> color_qnty;
    private javax.swing.JButton greenButton;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label l1;
    private java.awt.Label l2;
    private java.awt.Label l25;
    private java.awt.Label l26;
    private java.awt.Label l27;
    private java.awt.Label l28;
    private java.awt.Label l29;
    private java.awt.Label l3;
    private java.awt.Label l30;
    private java.awt.Label l31;
    private java.awt.Label l32;
    private java.awt.Label l33;
    private java.awt.Label l34;
    private java.awt.Label l35;
    private java.awt.Label l36;
    private java.awt.Label l37;
    private java.awt.Label l38;
    private java.awt.Label l39;
    private java.awt.Label l4;
    private java.awt.Label l40;
    private java.awt.Label l41;
    private java.awt.Label l42;
    private java.awt.Label l43;
    private java.awt.Label l44;
    private java.awt.Label l45;
    private java.awt.Label l46;
    private java.awt.Label l47;
    private java.awt.Label l48;
    private java.awt.Label l49;
    private java.awt.Label l5;
    private java.awt.Label l50;
    private java.awt.Label l51;
    private java.awt.Label l52;
    private java.awt.Label l53;
    private java.awt.Label l54;
    private java.awt.Label l55;
    private java.awt.Label l56;
    private java.awt.Label l6;
    private java.awt.Label l7;
    private java.awt.Label l8;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    public java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JButton pinkButton;
    private javax.swing.JButton purpleButton;
    private javax.swing.JButton redButton;
    private javax.swing.JButton whiteButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables

    private void hide_visibility() {
       
    //RED SHADES DISABLED
        label8.setVisible(false);
        label5.setVisible(false);
        label10.setVisible(false);
        label7.setVisible(false);
        label11.setVisible(false);
        label12.setVisible(false);
        label9.setVisible(false);
        label13.setVisible(false);
        //BULE SHADES DISABLE
 
l1.setVisible(false);
l2.setVisible(false);
l3.setVisible(false);

l4.setVisible(false);
l5.setVisible(false);
l6.setVisible(false);
l7.setVisible(false);
l8 .setVisible(false);

//GREEN SHADES DISABLED
a11.setVisible(false);
a12.setVisible(false);
a13.setVisible(false);
a14.setVisible(false);
a15.setVisible(false);
a16.setVisible(false);
a17.setVisible(false);
a18.setVisible(false);

//YELLOW
l25.setVisible(false);

        l26.setVisible(false);

        l27.setVisible(false);

        l28.setVisible(false);

        l29.setVisible(false);

        l30.setVisible(false);

        l31.setVisible(false);

        l32.setVisible(false);
        
        ///WHITE
        l33.setVisible(false);
l34.setVisible(false);
l35.setVisible(false);
l36.setVisible(false);
l37.setVisible(false);
l38.setVisible(false);
l39.setVisible(false);
l40.setVisible(false);

//PINK
l41.setVisible(false);
l42.setVisible(false);
l43.setVisible(false);
l44.setVisible(false);
l45.setVisible(false);
l46.setVisible(false);
l47.setVisible(false);
l48.setVisible(false);

//PURPLE
l49.setVisible(false);
l50.setVisible(false);
l51.setVisible(false);
l52.setVisible(false);
l53.setVisible(false);
l54.setVisible(false);
l55.setVisible(false);
l56.setVisible(false);
    }

   
        private void resize_imageDeafult() {
       ImageIcon icon=new ImageIcon((getClass().getResource("/interior/int2.jpg"))); 
       Image img =icon.getImage();
       Image imageScale = img.getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon scaledIcon=new ImageIcon(imageScale);
      jLabel12.setIcon(scaledIcon);
    }
}
