/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package signup;
import DealerLoginForm.DealerLogin;
import HomeMenu.Menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import jdbc.MysqlConnectionProvider;
import sgup.sgup;
import sulog.sulog;


/**
 *
 * @author JYOTIBA
 */
public class Signup extends javax.swing.JFrame {
boolean checked_user_name=false;
boolean  checked_name=false;
boolean checked_password=false;
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        unameValidation();
        nameValidation();
        passwordValidation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 45, 67));

        jPanel4.setBackground(new java.awt.Color(89, 199, 198));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/billbg.jpeg"))); // NOI18N
        jLabel10.setText("\\");

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/sg.png"))); // NOI18N

            jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

            jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

            jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(163, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(204, 204, 204));
            jLabel1.setText("Sign Up");

            jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

            username.setBackground(new java.awt.Color(36, 45, 67));
            username.setForeground(new java.awt.Color(204, 204, 204));
            username.setText("Username");
            username.setToolTipText("Username");
            username.setBorder(null);
            username.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    usernameFocusGained(evt);
                }
            });

            jLabel3.setBackground(new java.awt.Color(204, 204, 204));
            jLabel3.setForeground(new java.awt.Color(204, 204, 204));
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_name_25px.png"))); // NOI18N

            jLabel4.setBackground(new java.awt.Color(204, 204, 204));
            jLabel4.setForeground(new java.awt.Color(204, 204, 204));
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_username_25px.png"))); // NOI18N

            fname.setBackground(new java.awt.Color(36, 45, 67));
            fname.setForeground(new java.awt.Color(204, 204, 204));
            fname.setText("First name");
            fname.setToolTipText("First name");
            fname.setBorder(null);
            fname.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    fnameFocusGained(evt);
                }
            });

            jLabel5.setBackground(new java.awt.Color(204, 204, 204));
            jLabel5.setForeground(new java.awt.Color(204, 204, 204));
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_username_25px_1.png"))); // NOI18N

            lname.setBackground(new java.awt.Color(36, 45, 67));
            lname.setForeground(new java.awt.Color(204, 204, 204));
            lname.setText("Last name");
            lname.setToolTipText("Last name");
            lname.setBorder(null);
            lname.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    lnameFocusGained(evt);
                }
            });

            jLabel6.setBackground(new java.awt.Color(204, 204, 204));
            jLabel6.setForeground(new java.awt.Color(204, 204, 204));
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_iphone_25px.png"))); // NOI18N

            mobile.setBackground(new java.awt.Color(36, 45, 67));
            mobile.setForeground(new java.awt.Color(204, 204, 204));
            mobile.setText("Mobile No");
            mobile.setToolTipText("Mobile Number");
            mobile.setBorder(null);
            mobile.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    mobileFocusGained(evt);
                }
            });

            email.setBackground(new java.awt.Color(36, 45, 67));
            email.setForeground(new java.awt.Color(204, 204, 204));
            email.setText("Email");
            email.setToolTipText("Email");
            email.setBorder(null);
            email.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    emailFocusGained(evt);
                }
            });

            jLabel7.setBackground(new java.awt.Color(204, 204, 204));
            jLabel7.setForeground(new java.awt.Color(204, 204, 204));
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_secured_letter_25px.png"))); // NOI18N

            jLabel8.setBackground(new java.awt.Color(204, 204, 204));
            jLabel8.setForeground(new java.awt.Color(204, 204, 204));
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_password_25px.png"))); // NOI18N

            password.setBackground(new java.awt.Color(36, 45, 67));
            password.setForeground(new java.awt.Color(204, 204, 204));
            password.setText("jPasswordField1");
            password.setToolTipText("password");
            password.setBorder(null);
            password.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    passwordFocusGained(evt);
                }
            });

            jLabel9.setBackground(new java.awt.Color(204, 204, 204));
            jLabel9.setForeground(new java.awt.Color(204, 204, 204));
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/icons8_address_25px.png"))); // NOI18N

            addr.setBackground(new java.awt.Color(36, 45, 67));
            addr.setForeground(new java.awt.Color(204, 204, 204));
            addr.setText("Address");
            addr.setToolTipText("Address");
            addr.setBorder(null);
            addr.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    addrFocusGained(evt);
                }
            });

            jPanel1.setBackground(new java.awt.Color(36, 45, 67));
            jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            jPanel1.setForeground(new java.awt.Color(255, 255, 255));

            jLabel11.setBackground(new java.awt.Color(36, 45, 67));
            jLabel11.setForeground(new java.awt.Color(204, 204, 204));
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel11.setText("Submit");
            jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel11MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator4)
                                        .addComponent(username)
                                        .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(jSeparator5)
                                        .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(jSeparator6)
                                        .addComponent(mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(jSeparator7)
                                        .addComponent(jSeparator8)
                                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(jSeparator9)
                                        .addComponent(password)
                                        .addComponent(addr, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(jSeparator10)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(54, Short.MAX_VALUE))))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         try{
             String uname=username.getText();
             String pass=password.getText();
             
             String first_name=fname.getText();
             String last_name=lname.getText();
             String user_phoneNo=mobile.getText();
             String u_email=email.getText();
             String address=addr.getText();
              //open connection
           
             if (validData()) {
           MysqlConnectionProvider p=new MysqlConnectionProvider();
           p.InsertData(uname,pass,first_name,last_name,user_phoneNo,u_email,address);
         sgup su=new sgup();
         su.setVisible(true);
           dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Enter valid Data");
        }
          
                 
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
         
         dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
        fname.setText("");
    }//GEN-LAST:event_fnameFocusGained

    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
        // TODO add your handling code here:
        lname.setText("");
    }//GEN-LAST:event_lnameFocusGained

    private void mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusGained
        // TODO add your handling code here:
        mobile.setText("");
    }//GEN-LAST:event_mobileFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void addrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrFocusGained
        // TODO add your handling code here:
        addr.setText("");
    }//GEN-LAST:event_addrFocusGained

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private boolean validData() {
    
        {
        if (unameValidation() && passwordValidation() && phoneNoValidation() && emailValidation()) {
            return true;
        } else {
            if(!nameValidation())
            { JOptionPane.showMessageDialog(rootPane, "Please enter valid Name!!!!");
            
            }   
            else if (!passwordValidation())
            {    JOptionPane.showMessageDialog(rootPane, "Please Enter Strong password !!!!");
            
          }
           // else if(!checked_ph)
           // {    JOptionPane.showMessageDialog(rootPane, "ENTER VALID PHONE NUMBER !!!!");
          // }
            else if(phoneNoValidation()){
                 JOptionPane.showMessageDialog(rootPane, "Please Enter valid Phone Number !!!!");
                
            }
            else if (unameValidation())
            {     JOptionPane.showMessageDialog(rootPane, "Please Enter valid username!!!!");
           }
            else if(emailValidation())
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Email !!!!");
            return false;
        }
        
    }
    }
    private boolean unameValidation() {
       
     String User_name = username.getText();
        String noSpaceStr=User_name.replaceAll("\\s","");
        username.setText(noSpaceStr);
        if (User_name.length() != 0) {
            try{
                MysqlConnectionProvider rs=new MysqlConnectionProvider();
              ResultSet result=rs.MySqlResultSet("select * from `asian_paints`.`user_details`");
                while(result.next())
                {   String Username=result.getString(2);
                    System.out.println(Username);
                    if(User_name.equals(Username)){
                        JOptionPane.showMessageDialog(rootPane,"UserName Already Exist");
                        username.setText(" ");
                        return false;
                    }
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
          

        } 
        return true;
    }  

    private boolean nameValidation() {
       //To change body of generated methods, choose Tools | Templates.
    
     String fName = fname.getText();
     String lName=lname.getText();
     String noSpaceStr=fName.replaceAll("\\s","");
      String lnoSpaceStr=fName.replaceAll("\\s","");
     fname.setText(noSpaceStr);
     lname.setText(lnoSpaceStr);
        if (!fName.matches("^[0-9]*$")&&!lName.matches("^[0-9]*$")) {
           
            return true;
        }
    return false;
    }

    private boolean passwordValidation() {
        
    
     try {
        String user_password=password.getText();
        String noSpaceStr=user_password.replaceAll("\\s","");
        password.setText(noSpaceStr);
        if (!user_password.isEmpty()  ) {
            //return true;
            Pattern p =Pattern.compile("((?=.*[0-9])(?=.*[A-Z])(?=.*[@%#$]).{8,20})");//,Pattern.CASE_INSENSITIVE);
            Matcher m =p.matcher(user_password);
            if(m.matches())
                return true;
            else
                return false;
          
            
        } 
        }
        catch (Exception e){
            System.out.println(e);
        }
     return false;
    }
     /* private boolean isSpecialChararcter(String password) {
       Pattern p =Pattern.compile("((?=.*[0-9])(?=.*[A-Z])(?=.*[@%#$]).{8,20})");//,Pattern.CASE_INSENSITIVE);
       Matcher m =p.matcher(password);
       if(m.matches())
           return true;
       else
            return false;
    }*/

    /*private int isContainNumber(String password) {
        int count =0;
        for(int i =0;i<password.length()-1;i++)
            if (Character.isDigit(password.charAt(i)))
                count++;
                
               return count;
    }*/

    private boolean phoneNoValidation() {
         String user_phone = mobile.getText();
       if( user_phone.charAt(0)=='0')
       {
           mobile.setText(user_phone.substring(1));
       } 
       if (user_phone.length() == 10 ) {
            return true;
           //this.checked_ph=true;
        }
       return false;
    }

    private boolean emailValidation() {
   if(email.getText().endsWith("@gmail.com"))
   {
       return true;
   }
        
        return false;
    
    }
}

